name: Tips
main: net.namedfork.bukkit.Tips.Tips
version: 1.1
author: Jesús A. Álvarez
authorEmail: zydeco@namedfork.net
authorUrl: http://namedfork.net
commands:
  tips:
    description: reload tips
    usage: 'Usage: /tips reload'
    permission: tips.reload
permissions:
  tips.reload:
    description: Allows to reload tips
    default: op
  tips.receive.*:
    description: Receive all the tips
    default: false
